In [25]:
import torch
import os

# 模型保存
## save(net): 整個網路模型
## save(net.state_dict()): 僅保留模型的參數

In [26]:
x = torch.unsqueeze(torch.linspace(-1, 1, 100), dim=1)  # x data (tensor), shape=(100, 1)
y = x.pow(2) + 0.2*torch.rand(x.size())  # noisy y data (tensor), shape=(100, 1)
net1 = torch.nn.Sequential(
    torch.nn.Linear(1, 10),
    torch.nn.ReLU(),
    torch.nn.Linear(10, 1)
)
optimizer = torch.optim.SGD(net_save.parameters(), lr=0.5)
loss_func = torch.nn.MSELoss()

for _ in range(5):
    prediction = net1(x)
    loss = loss_func(prediction, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

torch.save(net1, 'Data/Model/net.pt')  # save entire net
torch.save(net1.state_dict(), 'Data/Model/net_params.pt')   # save only the parameters
print('儲存目錄下的檔案: ', os.listdir('Data/Model'))
print('整個網路模型檔案大小: ', os.path.getsize('Data/Model/net.pt'))
print('網路參數檔案大小: ', os.path.getsize('Data/Model/net_params.pt'))
print('\nnet1 parameters:\n')
for parameters in net1.parameters():
    print(parameters)

儲存目錄下的檔案:  ['net.pt', 'net_params.pt']
整個網路模型檔案大小:  2463
網路參數檔案大小:  1631

net1 parameters:

Parameter containing:
tensor([[-0.9415],
        [-0.0521],
        [ 0.5732],
        [-0.7731],
        [ 0.3686],
        [-0.9445],
        [ 0.8669],
        [-0.5663],
        [ 0.5987],
        [-0.0717]], requires_grad=True)
Parameter containing:
tensor([-0.0486,  0.8240, -0.8701, -0.5211,  0.7508,  0.6154,  0.9927,  0.6588,
         0.8596,  0.9381], requires_grad=True)
Parameter containing:
tensor([[ 0.1179, -0.0301,  0.1269,  0.1482, -0.1920, -0.2146, -0.2069,  0.2380,
          0.1197,  0.1031]], requires_grad=True)
Parameter containing:
tensor([-0.1226], requires_grad=True)


# 模型讀取
## 整個網路

In [27]:
net2 = torch.load('Data/Model/net.pt')
print(net2)
print('\nnet2 parameters:\n')
for parameters in net2.parameters():
    print(parameters)

Sequential(
  (0): Linear(in_features=1, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=1, bias=True)
)

net2 parameters:

Parameter containing:
tensor([[-0.9415],
        [-0.0521],
        [ 0.5732],
        [-0.7731],
        [ 0.3686],
        [-0.9445],
        [ 0.8669],
        [-0.5663],
        [ 0.5987],
        [-0.0717]], requires_grad=True)
Parameter containing:
tensor([-0.0486,  0.8240, -0.8701, -0.5211,  0.7508,  0.6154,  0.9927,  0.6588,
         0.8596,  0.9381], requires_grad=True)
Parameter containing:
tensor([[ 0.1179, -0.0301,  0.1269,  0.1482, -0.1920, -0.2146, -0.2069,  0.2380,
          0.1197,  0.1031]], requires_grad=True)
Parameter containing:
tensor([-0.1226], requires_grad=True)


## 模型參數
### 需重寫一遍模型再將參數導入模型中

In [28]:
# restore only the parameters in net1 to net3
net3 = torch.nn.Sequential(
    torch.nn.Linear(1, 10),
    torch.nn.ReLU(),
    torch.nn.Linear(10, 1)
)

# copy net1's parameters into net3
net3.load_state_dict(torch.load('Data/Model/net_params.pt'))
print(net3)
print('\nnet3 parameters:\n')
for parameters in net3.parameters():
    print(parameters)

Sequential(
  (0): Linear(in_features=1, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=1, bias=True)
)

net3 parameters:

Parameter containing:
tensor([[-0.9415],
        [-0.0521],
        [ 0.5732],
        [-0.7731],
        [ 0.3686],
        [-0.9445],
        [ 0.8669],
        [-0.5663],
        [ 0.5987],
        [-0.0717]], requires_grad=True)
Parameter containing:
tensor([-0.0486,  0.8240, -0.8701, -0.5211,  0.7508,  0.6154,  0.9927,  0.6588,
         0.8596,  0.9381], requires_grad=True)
Parameter containing:
tensor([[ 0.1179, -0.0301,  0.1269,  0.1482, -0.1920, -0.2146, -0.2069,  0.2380,
          0.1197,  0.1031]], requires_grad=True)
Parameter containing:
tensor([-0.1226], requires_grad=True)


# GPU訓練
## 數據, 網路模型, 損失函數可用GPU加速
### 可用 .cuda() or to(gpu)的方式調用GPU
### 也可設置自動決定device
### device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [29]:
torch.cuda.is_available()

True

In [30]:
tensor = torch.tensor([1, 2, 3])
print('原始tensor: ', tensor.device)
tensor = tensor.cuda()
print('調用GPU: ', tensor.device)
tensor = tensor.cpu()
print('調用cpu: ', tensor.device)

原始tensor:  cpu
調用GPU:  cuda:0
調用cpu:  cpu


In [31]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')  # 根據情況決定device
gpu = torch.device('cuda')
cpu = torch.device('cpu')
tensor = torch.tensor([1, 2, 3])
print('原始tensor: ', tensor.device)
tensor = tensor.to(gpu)
print('調用GPU: ', tensor.device)
tensor = tensor.to(cpu)
print('調用cpu: ', tensor.device)

原始tensor:  cpu
調用GPU:  cuda:0
調用cpu:  cpu
