In [32]:
import torch
import numpy as np
import torchvision.transforms as transforms
from PIL import Image
import cv2

# Torch型別轉換
## Torch & Numpy & list

In [25]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)  
tensor2array = torch_data.numpy()
array2list =  np_data.tolist()
# 轉Numpy時必須確保是 在cpu上運算 且 requires_grad=False
# .detach(): requires_grad變為False
tensor_gpu_requires_grad2array= torch_data.cpu().detach().numpy()  
print('torch_data:\n', torch_data, type(torch_data))
print('\ntensor2array:\n', tensor2array, type(tensor2array))
print('array2list:\n', array2list, type(array2list))
print('tensor_gpu_requires_grad2array:\n', tensor_gpu_requires_grad2array, type(tensor_gpu_requires_grad2array))

torch_data:
 tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) <class 'torch.Tensor'>

tensor2array:
 [[0 1 2]
 [3 4 5]] <class 'numpy.ndarray'>
array2list:
 [[0, 1, 2], [3, 4, 5]] <class 'list'>
tensor_gpu_requires_grad2array:
 [[0 1 2]
 [3 4 5]] <class 'numpy.ndarray'>


## 簡單運算(和Numpy類似)

In [20]:
# abs 绝对值计算
data = [-1, -2, 1, 2]
tensor_int64 = torch.tensor(data)
print('tensor_int64:\n', tensor_int64, tensor_int64.dtype)
tensor_float32 = tensor_int64.type(torch.FloatTensor)  # .type()做 dtype的變換
print('tensor_float32:\n', tensor_float32, tensor_float32.dtype)
# tensor = torch.FloatTensor(data)  # 直接創建
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor_float32)      # [1 2 1 2]
)

# sin   三角函数 sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor_float32)  # [-0.8415 -0.9093  0.8415  0.9093]
)

# mean  均值
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),         # 0.0
    '\ntorch: ', torch.mean(tensor_float32)     # 0.0
)

tensor_int64:
 tensor([-1, -2,  1,  2]) torch.int64
tensor_float32:
 tensor([-1., -2.,  1.,  2.]) torch.float32

abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])

sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])

mean 
numpy:  0.0 
torch:  tensor(0.)


# transforms
## transforms.ToTensor()

In [35]:
img_path = './Data/hymenoptera_data/train/0/0013035.jpg'
img_PIL = Image.open(img_path)
img_CV2 = cv2.imread(img_path)

# 創建一個ToTensor這個class的物件 
tensor_trans = transforms.ToTensor()  
# 調用ToTensor這個class的 __call__方法, 轉為tensor, 可傳入PIL Image or np.array
img_PIL2tensor = tensor_trans(img_PIL)        
img_CV22tensor = tensor_trans(img_CV2)
print('type(img_PIL2tensor): ', type(img_PIL2tensor))
print('type(img_PIL2tensor): ', type(img_PIL2tensor))

type(img_PIL2tensor):  <class 'torch.Tensor'>
type(img_PIL2tensor):  <class 'torch.Tensor'>


## transforms.ToPILImage()

In [39]:
tensor_trans = transforms.ToPILImage()
img_PIL = tensor_trans(img_PIL2tensor)  # 可傳入PIL Image or np.array
type(img_PIL)
# img_PIL.show()

PIL.Image.Image

## transforms.Normalize()

In [43]:
# Normalize
# output[channel] = (input[channel] - mean[channel]) / std[channel]
image_path = './Data/hymenoptera_data/train/0/0013035.jpg'
img = Image.open(image_path)
trans_toTensor = transforms.ToTensor()
img_tensor = trans_toTensor(img)
print(img_tensor[0][0][0])
# 均值, 標準差, 僅能輸入tensor類型
trans_norm = transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])  # RGB
img_norm = trans_norm(img_tensor)
print(img_norm[0][0][0])  # out = (input - mean)/ std
print((0.3137 - 0.5) / 0.5)

tensor(0.3137)
tensor(-0.3725)
-0.37260000000000004


## transforms.Resize()

In [53]:
# Resize
image_path = './Data/hymenoptera_data/train/0/0013035.jpg'
img = Image.open(image_path)
print(type(img))
# Resize the input image to the given size.
#     If the image is torch Tensor, it is expected
#     to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions
# 只改長寬, 只改[..., H, W], 所以輸入為(h, w) 2維
trans_resize = transforms.Resize((128, 128))  # 僅能傳去PIL Image
img_PIL_resize = trans_resize(img)
print(type(img_PIL_resize))  # PIL Image
trans_toTensor = transforms.ToTensor()
img_tensor_resize = trans_toTensor(img_PIL_resize)
print(img_tensor_resize.shape)

# # 可視化
# trans = transforms.ToPILImage()
# img = trans(img_tensor_resize)
# img.show()

<class 'PIL.JpegImagePlugin.JpegImageFile'>
<class 'PIL.Image.Image'>
torch.Size([3, 128, 128])


## transforms.Compose()

In [60]:
# Compose, Resize ---2
image_path = './Data/hymenoptera_data/train/0/0013035.jpg'
img = Image.open(image_path)
print(img.size)
trans_toTensor = transforms.ToTensor()
trans_resize2 = transforms.Resize(224)  # 僅傳入一個數值就等比縮放
# 把所有轉換存在一起的概念, 依序執行
trans_Compose = transforms.Compose([
    trans_resize2,
    trans_toTensor
])
img_resize2 = trans_Compose(img)
print(img_resize2.shape)


(768, 512)
torch.Size([3, 224, 336])


## transforms.RandomCrop()

In [69]:
# Compose, Resize ---2
image_path = './Data/hymenoptera_data/train/0/0013035.jpg'
img = Image.open(image_path)
img.show()
print(img.size)
# 指定大小, 隨機裁剪出該大小的圖片
trans_random = transforms.RandomCrop((224, 100))  
# 把所有轉換存在一起的概念, 依序執行
trans_Compose = transforms.Compose([
    trans_random,
    trans_toTensor
])
img_resize2 = trans_Compose(img)
print(img_resize2.shape)
# # 可視化
trans = transforms.ToPILImage()
img = trans(img_resize2)
img.show()

(768, 512)
torch.Size([3, 224, 100])
