In [2]:
import torch
import numpy as np
import torchvision.transforms as transforms
from PIL import Image
import cv2

# Torch常用運算
## Torch & Numpy & list

In [3]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)  
tensor2array = torch_data.numpy()
array2list =  np_data.tolist()
# 轉Numpy時必須確保是 在cpu上運算 且 requires_grad=False
# .detach(): requires_grad變為False
tensor_gpu_requires_grad2array= torch_data.cpu().detach().numpy()  
print('torch_data:\n', torch_data, type(torch_data))
print('\ntensor2array:\n', tensor2array, type(tensor2array))
print('array2list:\n', array2list, type(array2list))
print('tensor_gpu_requires_grad2array:\n', tensor_gpu_requires_grad2array, type(tensor_gpu_requires_grad2array))

torch_data:
 tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) <class 'torch.Tensor'>

tensor2array:
 [[0 1 2]
 [3 4 5]] <class 'numpy.ndarray'>
array2list:
 [[0, 1, 2], [3, 4, 5]] <class 'list'>
tensor_gpu_requires_grad2array:
 [[0 1 2]
 [3 4 5]] <class 'numpy.ndarray'>
torch_view:
 tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32) torch.Size([6])


## 簡單運算(和Numpy類似)

In [4]:
# abs 绝对值计算
data = [-1, -2, 1, 2]
tensor_int64 = torch.tensor(data)
print('tensor_int64:\n', tensor_int64, tensor_int64.dtype)
tensor_float32 = tensor_int64.type(torch.FloatTensor)  # .type()做 dtype的變換
print('tensor_float32:\n', tensor_float32, tensor_float32.dtype)
# tensor = torch.FloatTensor(data)  # 直接創建
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor_float32)      # [1 2 1 2]
)

# sin   三角函数 sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor_float32)  # [-0.8415 -0.9093  0.8415  0.9093]
)

# mean  均值
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),         # 0.0
    '\ntorch: ', torch.mean(tensor_float32)     # 0.0
)

tensor_int64:
 tensor([-1, -2,  1,  2]) torch.int64
tensor_float32:
 tensor([-1., -2.,  1.,  2.]) torch.float32

abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])

sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])

mean 
numpy:  0.0 
torch:  tensor(0.)


## Reshape

In [7]:
tensor1 = torch.empty([2, 3])
tensor2 = tensor1.view(-1)
print('tensor1:\n', tensor1.shape)
print('tensor2.shape: ', tensor2.shape)

tensor1:
 torch.Size([2, 3])
tensor2.shape:  torch.Size([6])


## 常用屬性: