In [45]:
import torch
import numpy as np
import torchvision.transforms as transforms
from PIL import Image
import cv2 

# Torch常用方法

## 加減乘除

In [46]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1, 2, 3])
add = torch.add(t1, t2)
subtract = torch.subtract(t1, t2)
multiply = torch.multiply(t1, t2)
divide = torch.divide(t1, t2)
print('add: ', add)
print('subtract: ', subtract)
print('multiply: ', multiply)
print('divide: ', divide)

add:  tensor([2, 4, 6])
subtract:  tensor([0, 0, 0])
multiply:  tensor([1, 4, 9])
divide:  tensor([1., 1., 1.])


## 取值

In [47]:
t1 = torch.tensor([1.3, 2.8, -3.4])
_abs = torch.abs(t1)  # 絕對值
ceil = torch.ceil(t1)  # 向上取整
floor = torch.floor(t1)  # 向下取整
_round = torch.round(t1)  # 四捨五入
neg = torch.neg(t1)  # 相反數
print('_abs: ', _abs)
print('ceil: ', ceil)
print('floor: ', floor)
print('divide: ', _round)
print('neg: ', neg)

_abs:  tensor([1.3000, 2.8000, 3.4000])
ceil:  tensor([ 2.,  3., -3.])
floor:  tensor([ 1.,  2., -4.])
divide:  tensor([ 1.,  3., -3.])
neg:  tensor([-1.3000, -2.8000,  3.4000])


In [48]:
t = torch.tensor([1.3, 2.8, -3.4])
t.abs_()  # 直接修改t的值
print('t: ', t)

t:  tensor([1.3000, 2.8000, 3.4000])


In [49]:
t = torch.tensor([1.3, 2.8, -3.4])
t.exp_()  # 直接修改t的值
print('t: ', t)

t:  tensor([ 3.6693, 16.4446,  0.0334])


## torch.sin()

In [18]:
data = [-1, -2, 1., 2]
tensor_float32 = torch.tensor(data).float()
print('tensor_float32:\n', tensor_float32, tensor_float32.dtype)
array = np.sin(data)
tensor = torch.sin(tensor_float32)
print('array:\n', array)
print('tensor:\n', tensor)

tensor_float32:
 tensor([-1., -2.,  1.,  2.]) torch.float32
array:
 [-0.84147098 -0.90929743  0.84147098  0.90929743]
tensor:
 tensor([-0.8415, -0.9093,  0.8415,  0.9093])


## torch.mean()

In [10]:
data = [-1, -2, 1., 2]
tensor_float32 = torch.tensor(data).float()
print('tensor_float32:\n', tensor_float32, tensor_float32.dtype)
array = np.mean(data)  
tensor = torch.mean(tensor_float32)  # 平均值
print('array:\n', array)
print('tensor:\n', tensor)

tensor_float32:
 tensor([-1., -2.,  1.,  2.]) torch.float32
array:
 0.0
tensor:
 tensor(0.)


## torch.dist()

In [12]:
t1 = torch.tensor([1, 5, 3.])
t2 = torch.tensor([1, 2., 3])
print(f'{t1}和{t2}的距離: ', torch.dist(t1, t2))

tensor([1., 5., 3.])和tensor([1., 2., 3.])的距離:  tensor(3.)


## torch.nonzero()

In [22]:
x = torch.tensor([0, 1, 2 ,3 ,0])
y = torch.nonzero(x)
print('x: ', x)
print('y:\n', y, y.size())

x:  tensor([0, 1, 2, 3, 0])
y:
 tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])


# 索引

## torch.index_select()

In [28]:
data = torch.arange(12).view(3, 4)
indices = torch.tensor([1, 2])
t1 = torch.index_select(input=data, dim=1, index=indices)  # 可指定dim，高維操作中比較方便
print('data:\n', data)
print('t1:\n', t1)

data:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
t1:
 tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])


# 維度命名

In [58]:
name = ['B', 'C', 'H', 'W']
x = torch.rand((2, 3, 3, 3), names=name)
x_sum = x.sum(dim='C', keepdim=True)
x_0 = x.select(dim='B', index=0)  # 取出第0張影像
x_0 = x.select(dim='B', index=1)
print('x_sum.size(): ', x_sum.size())
print('x.size(): ', x.size())
print('x_0.size(): ', x_0.size())

x_sum.size():  torch.Size([2, 1, 3, 3])
x.size():  torch.Size([2, 3, 3, 3])
x_0.size():  torch.Size([3, 3, 3])


# 維度變換

In [52]:
tensor1 = torch.empty([2, 3])
tensor2 = tensor1.view(-1)
print('tensor1:\n', tensor1.shape)
print('tensor2.shape: ', tensor2.shape)

tensor1:
 torch.Size([2, 3])
tensor2.shape:  torch.Size([6])


## 降維增維

In [53]:
tensor = torch.empty(5, 1)
print(tensor.shape)
tensor1 = torch.squeeze(tensor, axis=1)
print(tensor1.shape)
tensor2 = torch.squeeze(tensor, axis=0)
print(tensor2.shape)

torch.Size([5, 1])
torch.Size([5])
torch.Size([5, 1])


In [43]:
tensor = torch.empty(5)
print(tensor.shape)
t1 = torch.unsqueeze(tensor, axis=1)
print('t1.shape: ', t1.shape)
t2 = torch.unsqueeze(tensor, axis=0)
print('t2.shape: ', t2.shape)
t3 = tensor[:, None]
print('t3.shape: ', t3.shape)
t4 = tensor[None, :]
print('t4.shape: ', t4.shape)

torch.Size([5])
t1.shape:  torch.Size([5, 1])
t2.shape:  torch.Size([1, 5])
t3.shape:  torch.Size([5, 1])
t4.shape:  torch.Size([1, 5])


## 維度切分

### torch.chunk()

In [31]:
t = torch.arange(12).reshape(4, 3)
tc = torch.chunk(t, 4, dim=0)  # 返回的是t的view
print('t:\n', t)
print('tc:\n', tc)

t:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tc:
 (tensor([[0, 1, 2]]), tensor([[3, 4, 5]]), tensor([[6, 7, 8]]), tensor([[ 9, 10, 11]]))


### torch.split()

In [32]:
t = torch.arange(12).reshape(4, 3)
ts = torch.split(t, [1, 3], dim=0)  # 返回的是t的view
print('t:\n', t)
print('tc:\n', ts)

t:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tc:
 (tensor([[0, 1, 2]]), tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))


# Tensor合併

## torch.cat(): 拼接

In [33]:
t1 = torch.ones((1, 5, 5))
t2 = torch.ones((1, 5, 5))
t3 = torch.ones((1, 5, 5))
print('t1 ~ t3.shape: ', t1.shape)
x = torch.cat((t1, t2, t3), dim=0)
print('x.shape: ', x.shape)
x1 = torch.cat((t1, t2, t3), dim=1)
print('x1.shape: ', x1.shape)
x2 = torch.cat((t1, t2, t3), dim=2)
print('x2.shape: ', x2.shape)

t1 ~ t3.shape:  torch.Size([1, 5, 5])
x.shape:  torch.Size([3, 5, 5])
x1.shape:  torch.Size([1, 15, 5])
x2.shape:  torch.Size([1, 5, 15])


## torch.stack(): 堆疊

In [36]:
t1 = torch.ones((1, 5, 5))
t2 = torch.ones((1, 5, 5))
t3 = torch.ones((1, 5, 5))
print('t1 ~ t3.shape: ', t1.shape)
x = torch.stack((t1, t2, t3), dim=0)  #會新增一個維度
print('x.shape: ', x.shape)
x1 = torch.stack((t1, t2, t3), dim=1)
print('x1.shape: ', x1.shape)
x2 = torch.stack((t1, t2, t3), dim=2)
print('x2.shape: ', x2.shape)

t1 ~ t3.shape:  torch.Size([1, 5, 5])
x.shape:  torch.Size([3, 1, 5, 5])
x1.shape:  torch.Size([1, 3, 5, 5])
x2.shape:  torch.Size([1, 5, 3, 5])


# 型態變換

##  Torch & Numpy & list轉換

In [15]:
np_data = np.arange(6).reshape((2, 3))
tensor = torch.tensor([1, 2, 3])
torch_data = torch.from_numpy(np_data)  # array to tensor
tensor2array = torch_data.numpy()  # tensor to array(需要.cpu().detach()才可以轉)
array2list =  np_data.tolist()  # array to list
tensor1 = tensor.tolist()  # tensor to list
print('tensor1:\n', tensor1, type(tensor1))
print('torch_data:\n', torch_data, type(torch_data))
print('\ntensor2array:\n', tensor2array, type(tensor2array))
print('array2list:\n', array2list, type(array2list))

tensor1:
 [1, 2, 3] <class 'list'>
torch_data:
 tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) <class 'torch.Tensor'>

tensor2array:
 [[0 1 2]
 [3 4 5]] <class 'numpy.ndarray'>
array2list:
 [[0, 1, 2], [3, 4, 5]] <class 'list'>


## tensor dtype轉換

In [16]:
t1 = torch.tensor([1, 2, 3])
print('t1.dtype: ', t1.dtype)
t2 = t1.float()  
print('t2.dtype: ', t2.dtype)
t3 = t1.long()
print('t3.dtype: ', t3.dtype)

t1.dtype:  torch.int64
t2.dtype:  torch.float32
t3.dtype:  torch.int64


In [17]:
t1 = torch.tensor([1, 2, 3])
print('t1.dtype: ', t1.dtype)
t2 = t1.type(torch.FloatTensor)  
print('t2.dtype: ', t2.dtype)
t3 = t1.type(torch.LongTensor)
print('t3.dtype: ', t3.dtype)

t1.dtype:  torch.int64
t2.dtype:  torch.float32
t3.dtype:  torch.int64


# 常用屬性

## tensor.numel()

In [20]:
t1 = torch.empty([2, 3])
t2 = t1.numel()  # 總元素個數
print(t1.shape)
print(t2)

torch.Size([2, 3])
6


## tensor.clone()

In [44]:
t1 = torch.tensor([1, 2, 3])
t2 = t1.clone()
print(id(t1))
print(id(t2))

2220084371344
2220464854736


## tensor.clamp()

In [11]:
x = torch.rand(4)
print('x: ', x)
y = x.clamp(min=-0.5, max=0.5)
print('y: ', y)

x:  tensor([0.1033, 0.6847, 0.3334, 0.4812])
y:  tensor([0.1033, 0.5000, 0.3334, 0.4812])


## tensor.item()

In [13]:
x = torch.tensor([1])
print('x: ', x)
print('x.item(): ', x.item())  # 速度慢少用

x:  tensor([1])
x.item():  1


## tensor.detach()

In [25]:
t1 = torch.tensor([1., 2, 3], requires_grad=True)
print('t1: ', t1)
print('t1.detach(): ', t1.detach())  # set requires_grad=False

t1:  tensor([1., 2., 3.], requires_grad=True)
t1.detach():  tensor([1., 2., 3.])


## tensor.squeeze()

In [40]:
t = torch.empty((3, 1))
print('t.shape: ', t.shape)
print('t.squeeze(0).shape: ', t.squeeze(0).shape)
print('t.squeeze(1).shape: ', t.squeeze(1).shape)

t.shape:  torch.Size([3, 1])
t.squeeze(0).shape:  torch.Size([3, 1])
t.squeeze(1).shape:  torch.Size([3])


## tensor.unsqueeze()

In [41]:
t = torch.empty((3, 1))
print('t.shape: ', t.shape)
print('t.unsqueeze(0).shape: ', t.unsqueeze(0).shape)
print('t.unsqueeze(1).shape: ', t.unsqueeze(1).shape)

t.shape:  torch.Size([3, 1])
t.unsqueeze(0).shape:  torch.Size([1, 3, 1])
t.unsqueeze(1).shape:  torch.Size([3, 1, 1])


## tensor.sum()

In [43]:
x = torch.rand((3, 1, 5, 3))
y = x.sum(dim=0)
z = x.sum(dim=0, keepdim=True)
print('x.size(): ', x.size())
print('y.size(): ', y.size())
print('z.size(): ', z.size())

x.size():  torch.Size([3, 1, 5, 3])
y.size():  torch.Size([1, 5, 3])
z.size():  torch.Size([1, 1, 5, 3])


## tensor.select():

In [48]:
x = torch.rand((3, 1, 5, 5))
x1 = x.select(dim=0, index=0)  # 選出第一章影像
print('x.size(): ', x.size())
print('x1.size(): ', x1.size())  # 選出第一章影像

x.size():  torch.Size([3, 1, 5, 5])
x1.size():  torch.Size([1, 5, 5])


# 廣播

In [34]:
t34 = torch.ones([3, 4])
t = t34 + 1  # 相當於加上一個 3*4大小都是1的tensor
print('t:\n', t)

t:
 tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [40]:
t34 = torch.ones([3, 4])
t14 = torch.ones([1, 4])  # 一個維度是1就可以發生廣播
t = t34 + t14  # 相當於加上一個 3*4大小都是1的tensor
print('t:\n', t)

t:
 tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [44]:
t31 = torch.arange(3).reshape(3, 1)
t13 = torch.arange(3).reshape(1, 3)
t = t31 + t13
'''
廣播:
0 1 2            0 0 0 
0 1 2     +      1 1 1
0 1 2            2 2 2 
'''
print('t:\n', t)

t:
 tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])
