# 創建數據
## 常用屬性:
### ndim: 維度 ex: 幾維空間裡面
### shape: ex: (3, 4)
### size: 總數, ex: 12

In [4]:
import numpy as np

cars = np.array([5, 10, 12, 6])
print("數據： ", cars)
print("維度： ", cars.ndim)
print("shape： ", cars.shape)
print("size： ", cars.size)

數據：  [ 5 10 12  6]
維度：  1
shape：  (4,)
size：  4


## 生成數據:
### 規則數據:

In [29]:
import numpy as np

print("np.zeros((2, 3)):\n", np.zeros((2, 3)))  # (2, 3) 都是0
print("np.ones((3, 2)):\n", np.ones((3, 2)))  # (2, 3) 都是0
print("np.full((2,3), 9):\n", np.full((2,3), 9))  # (2, 3) 都是9
# 創建速度較快可理解為placeholder, 用於數據必然會被取代掉的時候
print("np.empty((2,3)):\n", np.empty((2,3)))  

np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]
np.ones((3, 2)):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
np.full((2,3), 9):
 [[9 9 9]
 [9 9 9]]
np.empty((2,3)):
 [[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
data = np.array([
[1,2,3],
[4,5,6]
], dtype=np.int64)

# 產生一樣大小的矩陣
ones = np.ones(data.shape, dtype=data.dtype)
ones_like = np.ones_like(data)
empty = np.empty_like(data)
print("ones:", ones.shape, ones.dtype)
print("ones_like:", ones_like.shape, ones_like.dtype)
print("ones_like value:\n", ones_like)
print("empty_like value:\n", empty)

ones: (2, 3) int64
ones_like: (2, 3) int64
ones_like value:
 [[1 1 1]
 [1 1 1]]
empty_like value:
 [[1 1 1]
 [1 1 1]]


In [34]:
# arange類似python range
print("python range:", list(range(5)))
print("numpy arange:", np.arange(5))
# (start, end, step) 
print("python range:", list(range(3, 10, 2)))
print("numpy arange:", np.arange(3, 10, 2))

python range: [0, 1, 2, 3, 4]
numpy arange: [0 1 2 3 4]
python range: [3, 5, 7, 9]
numpy arange: [3 5 7 9]


In [36]:
# (start, end, num)
print("linspace:", np.linspace(-1, 1, 5))  # -1 ~ 1 取5的平均距離的點
print("5 segments:", np.linspace(-1, 1, 5, endpoint=False))  # 不包含結尾的點

linspace: [-1.  -0.5  0.   0.5  1. ]
5 segments: [-1.  -0.6 -0.2  0.2  0.6]


### 隨機數據: