In [2]:
import numpy as np

# 創建數據
## 常用屬性:
### ndim: 維度 ex: 幾維空間裡面
### shape: ex: (3, 4)
### size: 總數, ex: 12

In [4]:
import numpy as np

cars = np.array([5, 10, 12, 6])
print("數據： ", cars)
print("維度： ", cars.ndim)
print("shape： ", cars.shape)
print("size： ", cars.size)

數據：  [ 5 10 12  6]
維度：  1
shape：  (4,)
size：  4


## 規則數據:

In [29]:
import numpy as np

print("np.zeros((2, 3)):\n", np.zeros((2, 3)))  # (2, 3) 都是0
print("np.ones((3, 2)):\n", np.ones((3, 2)))  # (2, 3) 都是0
print("np.full((2,3), 9):\n", np.full((2,3), 9))  # (2, 3) 都是9
# 創建速度較快可理解為placeholder, 用於數據必然會被取代掉的時候
print("np.empty((2,3)):\n", np.empty((2,3)))  

np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]
np.ones((3, 2)):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
np.full((2,3), 9):
 [[9 9 9]
 [9 9 9]]
np.empty((2,3)):
 [[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
data = np.array([
[1,2,3],
[4,5,6]
], dtype=np.int64)

# 產生一樣大小的矩陣
ones = np.ones(data.shape, dtype=data.dtype)
ones_like = np.ones_like(data)
empty = np.empty_like(data)
print("ones:", ones.shape, ones.dtype)
print("ones_like:", ones_like.shape, ones_like.dtype)
print("ones_like value:\n", ones_like)
print("empty_like value:\n", empty)

ones: (2, 3) int64
ones_like: (2, 3) int64
ones_like value:
 [[1 1 1]
 [1 1 1]]
empty_like value:
 [[1 1 1]
 [1 1 1]]


In [34]:
# arange類似python range
print("python range:", list(range(5)))
print("numpy arange:", np.arange(5))
# (start, end, step) 
print("python range:", list(range(3, 10, 2)))
print("numpy arange:", np.arange(3, 10, 2))

python range: [0, 1, 2, 3, 4]
numpy arange: [0 1 2 3 4]
python range: [3, 5, 7, 9]
numpy arange: [3 5 7 9]


In [36]:
# (start, end, num)
print("linspace:", np.linspace(-1, 1, 5))  # -1 ~ 1 取5的平均距離的點
print("5 segments:", np.linspace(-1, 1, 5, endpoint=False))  # 不包含結尾的點

linspace: [-1.  -0.5  0.   0.5  1. ]
5 segments: [-1.  -0.6 -0.2  0.2  0.6]


## 隨機數據:
### 隨機生成數據

In [27]:
# 與Python內建的random相比，多了很多數據型態可使用
dim1, dim2 = 3, 2
# 兩個功能一樣寫法不同而已
print('0-1的隨機數:\n', np.random.random([dim1, dim2]))
print('0-1的隨機數:\n', np.random.rand(dim1, dim2))  
# 按照常態分佈去生成資料
print('常態分佈生成隨機數:\n', np.random.randn(dim1, dim2))
print('隨機整數:\n', np.random.randint(low=-3, high=6, size=[3, 2]))
print('常態分佈生成隨機數: ', np.random.normal(loc=1, scale=0.2, size=(1, 5)))  # 平均, 標準差

# (最低，最高，size)
print("均勻分布：", np.random.uniform(low=-1, high=1, size=(5, )))
# np.random.seed(2)  # 固定隨機, 之後隨機的數都會一樣

0-1的隨機數:
 [[0.11754967 0.70027353]
 [0.92584218 0.65980515]
 [0.28510163 0.03714075]]
0-1的隨機數:
 [[0.88768274 0.94663151]
 [0.41603207 0.23322921]
 [0.33193068 0.31919775]]
常態分佈生成隨機數:
 [[-0.82294776 -0.78554342]
 [-2.00312346 -1.21602521]
 [ 2.01297842 -1.9140059 ]]
隨機整數:
 [[ 0 -2]
 [ 3  1]
 [-2 -3]]
常態分佈生成隨機數:  [[0.88807644 1.11931007 0.80472851 1.06110491 1.04809758]]
均勻分布： [-0.68524031 -0.38101346 -0.85616295 -0.7962846  -0.29896   ]


### 隨機選擇數據

In [19]:
# 隨機選擇
data = np.array([2,1,3,4,6])
print('原始數據: ', data)
print("選一個：", np.random.choice(data))
print("選多個(可能重複)：", np.random.choice(data, size=3))
print("不重複的選多個(不放回)：", np.random.choice(data, size=3, replace=False))
print("帶權重的選擇：", np.random.choice(data, size=10, p=[0, 0, 0, 0.2, 0.8]))

原始數據:  [2 1 3 4 6]
選一個： 6
選多個(可能重複)： [6 2 6]
不重複的選多個(不放回)： [3 1 6]
帶權重的選擇： [6 6 4 6 6 4 6 4 6 6]
